### ISSUE TITLE
Foundation normalize.scss path broken

### ISSUE THREAD

**Issue by michaelBenin** [michaelBenin/react-ssr-spa#12]
Waiting on https://github.com/zurb/foundation-sites/pull/9458 to upgrade.

**Comment by ncoden** [comment]
https://github.com/zurb/foundation-sites/pull/9458 has been merged and `v6.3.0-rc2` will be available in the next days.

**Comment by ncoden** [comment]
@michaelBenin `v6.3.0-rc2` is available. The bug should be resolved. https://github.com/zurb/foundation-sites/releases/tag/v6.3.0-rc2

**Comment by michaelBenin** [comment]
Adding today. Thanks.

**Comment by michaelBenin** [comment]
@ncoden when do you think it will be published to npm?
